# Generated by Django 5.1.3 on 2024-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="news", verbose_name="Фото")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Статус"),
                ),
            ],
            options={
                "verbose_name_plural": "Новости",
            },
        ),
    ]
